import Vue from 'vue'
import App from './App.vue'

Vue.config.productionTip = false

import router from "@/router.js";

new Vue({
  render: h => h(App),
  router,
  data: {
    set: [
      {
        "author": "Chinua Achebe",
        "country": "Nigeria",
        "background": "static/things-fall-apart.jpg",
        "language": "English",
        "link": "https://en.wikipedia.org/wiki/Things_Fall_Apart\n",
        "pages": 209,
        "title": "Things Fall Apart",
        "year": 1958,
        "description": "Things Fall Apart is the first of three novels in Chinua Achebe's critically acclaimed African Trilogy. It is a classic narrative about Africa's cataclysmic encounter with Europe as it establishes a colonial presence on the continent. Told through the fictional experiences of Okonkwo, a wealthy and fearless Igbo warrior of Umuofia in the late 1800s, Things Fall Apart explores one man's futile resistance to the devaluing of his Igbo traditions by British political andreligious forces and his despair as his community capitulates to the powerful new order.    With more than 20 million copies sold and translated into fifty-seven languages, Things Fall Apart provides one of the most illuminating and permanent monuments to African experience. Achebe does not only capture life in a pre-colonial African village, he conveys the tragedy of the loss of that world while broadening our understanding of our contemporary realities.",
        "isbn": "121593",
        "status": "available"
      },
      {
        "author": "Hans Christian Andersen",
        "country": "Denmark",
        "background": "static/fairy-tales.jpg",
        "language": "Danish",
        "link": "https://en.wikipedia.org/wiki/Fairy_Tales_Told_for_Children._First_Collection.\n",
        "pages": 784,
        "title": "Fairy tales",
        "year": 1836,
        "description": "Fairy Tales Told for Children. First Collection is a collection of nine fairy tales by Hans Christian Andersen. The tales were published in a series of three installments by C. A. Reitzel in Copenhagen, Denmark between May 1835 and April 1837, and represent Andersen's first venture into the fairy tale genre.",
        "isbn": "121594",
        "status": "available"
      },
      {
        "author": "Dante Alighieri",
        "country": "Italy",
        "background": "static/the-divine-comedy.jpg",
        "language": "Italian",
        "link": "https://en.wikipedia.org/wiki/Divine_Comedy\n",
        "pages": 928,
        "title": "The Divine Comedy",
        "year": 1315,
        "description": "Belonging in the immortal company of the great works of literature, Dante Alighieri’s poetic masterpiece, The Divine Comedy, is a moving human drama, an unforgettable visionary journey through the infinite torment of Hell, up the arduous slopes of Purgatory, and on to the glorious realm of Paradise—the sphere of universal harmony and eternal salvation.",
        "isbn": "121595",
        "status": "waitlist"
      },
      {
        "author": "Unknown",
        "country": "Sumer and Akkadian Empire",
        "background": "static/the-epic-of-gilgamesh.jpg",
        "language": "Akkadian",
        "link": "https://en.wikipedia.org/wiki/Epic_of_Gilgamesh\n",
        "pages": 160,
        "title": "The Epic Of Gilgamesh",
        "year": -1700,
        "description": "The Epic of Gilgamesh is the oldest written chronicle in the world, composed three to four thousand years before Christ. It tells events in the life of a king in an ancient city of Mesopotamia. The text is revered, and the hero is an icon of Mesopotamia, equal in tradition to the Jewish hero David as told in the Bible or the Greek hero Achilles as told in the Iliad, both of which it precedes as literature and in some aspects it anticipates. For untold centuries, even into the last millennium before Christ, the children of what is now Iraq learned to read and write by copying Gilgamesh, just as once Greek children learned to read and write by copying the Iliad and just as before the 20th century in Europe and America children learned to read and write from the text of the Bible. References to Gilgamesh in daily speech were commonplace.The Epic of Gilgamesh is called an “epic” in the tradition of the Greek Iliad or the medieval Beowulf. Like epic poems, the central figure is admired for his prowess and power; he is a heroic warrior, whose greatest adventure is here recounted.",
        "isbn": "121596",
        "status": "available"
      },
      {
        "author": "Unknown",
        "country": "Achaemenid Empire",
        "background": "static/the-book-of-job.jpg",
        "language": "Hebrew",
        "link": "https://en.wikipedia.org/wiki/Book_of_Job\n",
        "pages": 176,
        "title": "The Book Of Job",
        "year": -600,
        "description": "The theme of The Book of Job is nothing less than human suffering and the transcendence of it: it pulses with moral energy, outrage, and spiritual insight. Now, The Book of Job has been rendered into English by the eminent translator and scholar Stephen Mitchell, whose versions of Rilke, Israeli poetry, and the Tao Te Ching have been widely praised. This is the first time ever that the Hebrew verse of Job has been translated into verse in any language, ancient or modern, and the result is a triumph.",
        "isbn": "121597",
        "status": "waitlist"
      },
      {
        "author": "Unknown",
        "country": "India/Iran/Iraq/Egypt/Tajikistan",
        "background": "static/one-thousand-and-one-nights.jpg",
        "language": "Arabic",
        "link": "https://en.wikipedia.org/wiki/One_Thousand_and_One_Nights\n",
        "pages": 288,
        "title": "One Thousand and One Nights",
        "year": 1200,
        "description": "King Shahryar kills a new wife every night, because he is afraid she will stop loving him. But his new bride Shahrazad has a clever plan to save herself. Her nightly stories--of Sinbad the Sailor, Ali Baba, and many other heroes and villains--are so engrossing that King Shahryar has to postpone her execution again and again... This illustrated edition brings together all the Arabian Nights tales in an original retelling by award-winning author Geraldine McCaughrean.",
        "isbn": "121598",
        "status": "available"
      },
      {
        "author": "Unknown",
        "country": "Iceland",
        "background": "static/njals-saga.jpg",
        "language": "Old Norse",
        "link": "https://en.wikipedia.org/wiki/Nj%C3%A1ls_saga\n",
        "pages": 384,
        "title": "Njál's Saga",
        "year": 1350,
        "description": "Written in the thirteenth century, Njal's Saga is a story that explores perennial human problems-from failed marriages to divided loyalties, from the law's inability to curb human passions to the terrible consequences when decent men and women are swept up in a tide of violence beyond their control. It is populated by memorable and complex characters like Gunnar of Hlidarendi, a powerful warrior with an aversion to killing, and the not-so-villainous Mord Valgardsson. Full of dreams, strange prophecies, violent power struggles, and fragile peace agreements, Njal's Saga tells the compelling story of a fifty-year blood feud that, despite its distance from us in time and place, is driven by passions familiar to us all.",
        "isbn": "121599",
        "status": "waitlist"
      },
      {
        "author": "Jane Austen",
        "country": "United Kingdom",
        "background": "static/pride-and-prejudice.jpg",
        "language": "English",
        "link": "https://en.wikipedia.org/wiki/Pride_and_Prejudice\n",
        "pages": 226,
        "title": "Pride and Prejudice",
        "year": 1813,
        "description": "Pride and Prejudice is a novel of manners by Jane Austen, first published in 1813. The story follows the main character, Elizabeth Bennet, as she deals with issues of manners, upbringing, morality, education, and marriage in the society of the landed gentry of the British Regency. Elizabeth is the second of five daughters of a country gentleman living near the fictional town of Meryton in Hertfordshire, near London.Page 2 of a letter from Jane Austen to her sister Cassandra (11 June 1799) in which she first mentions Pride and Prejudice, using its working title First Impressions.Set in England in the early 19th century, Pride and Prejudice tells the story of Mr and Mrs Bennet's five unmarried daughters after the rich and eligible Mr Bingley and his status-conscious friend, Mr Darcy, have moved into their neighbourhood. While Bingley takes an immediate liking to the eldest Bennet daughter, Jane, Darcy has difficulty adapting to local society and repeatedly clashes with the second-eldest Bennet daughter, Elizabeth.Though Austen set the story at the turn of the 19th century, it retains a fascination for modern readers, continuing near the top of lists of 'most loved books.' It has become one of the most popular novels in English literature, selling over 20 million copies, and receives considerable attention from literary scholars. Modern interest in the book has resulted in a number of dramatic adaptations and an abundance of novels and stories imitating Austen's memorable characters or themes.",
        "isbn": "121600",
        "status": "available"
      },
      {
        "author": "Honoré de Balzac",
        "country": "France",
        "background": "static/le-pere-goriot.jpg",
        "language": "French",
        "link": "https://en.wikipedia.org/wiki/Le_P%C3%A8re_Goriot\n",
        "pages": 443,
        "title": "Le Père Goriot",
        "year": 1835,
        "description": "This fine example of the French realist novel contrasts the social progress of an impoverished but ambitious aristocrat with the tale of a father, whose obsessive love for his daughters leads to his personal and financial ruin.",
        "isbn": "121601",
        "status": "waitlist"
      },
      {
        "author": "Samuel Beckett",
        "country": "Republic of Ireland",
        "background": "static/molloy-malone-dies-the-unnamable.jpg",
        "language": "French, English",
        "link": "https://en.wikipedia.org/wiki/Molloy_(novel)\n",
        "pages": 256,
        "title": "Molloy, Malone Dies, The Unnamable, the trilogy",
        "year": 1952,
        "description": "Few works of contemporary literature are so universally acclaimed as central to our understanding of the human experience as Nobel Prize winner Samuel Beckett’s famous trilogy. Molloy, the first of these masterpieces, appeared in French in 1951. It was followed seven months later by Malone Dies and two years later by The Unnamable. All three have been rendered into English by the author.",
        "isbn": "121602",
        "status": "available"
      },
      {
        "author": "Giovanni Boccaccio",
        "country": "Italy",
        "background": "static/the-decameron.jpg",
        "language": "Italian",
        "link": "https://en.wikipedia.org/wiki/The_Decameron\n",
        "pages": 1024,
        "title": "The Decameron",
        "year": 1351,
        "description": "In the summer of 1348, as the Black Death ravages their city, ten young Florentines take refuge in the countryside. They amuse themselves by each telling a story a day for the ten days they are destined to remain there—a hundred stories of love, adventure and surprising twists of fate. Less preoccupied with abstract concepts of morality or religion than with earthly values, the tales range from the bawdy Peronella hiding her lover in a tub to Ser Cepperello, who, despite his unholy effrontery, becomes a Saint. The result is a towering monument of European literature and a masterpiece of imaginative narrative.",
        "isbn": "121603",
        "status": "available"
      },
      {
        "author": "Jorge Luis Borges",
        "country": "Argentina",
        "background": "static/ficciones.jpg",
        "language": "Spanish",
        "link": "https://en.wikipedia.org/wiki/Ficciones\n",
        "pages": 224,
        "title": "Ficciones",
        "year": 1965,
        "description": "The seventeen pieces in Ficciones demonstrate the whirlwind of Borges’s genius and mirror the precision and potency of his intellect and inventiveness, his piercing irony, his skepticism, and his obsession with fantasy. Borges sends us on a journey into a compelling, bizarre, and profoundly resonant realm; we enter the fearful sphere of Pascal’s abyss, the surreal and literal labyrinth of books, and the iconography of eternal return. To enter the worlds in Ficciones is to enter the mind of Jorge Luis Borges, wherein lies Heaven, Hell, and everything in between.",
        "isbn": "121604",
        "status": "waitlist"
      },
      {
        "author": "Emily Brontë",
        "country": "United Kingdom",
        "background": "static/wuthering-heights.jpg",
        "language": "English",
        "link": "https://en.wikipedia.org/wiki/Wuthering_Heights\n",
        "pages": 342,
        "title": "Wuthering Heights",
        "year": 1847,
        "description": "Wuthering Heights, Emily Brontë's only novel, was published in 1847 under the pseudonym 'Ellis Bell. She died the following year, aged 30. It was written between October 1845 and June 1846, Wuthering Heights and Anne Brontë's Agnes Grey were accepted by publisher Thomas Newby before the success of their sister Charlotte's novel Jane Eyre. ",
        "isbn": "121605",
        "status": "waitlist"
      },
      {
        "author": "Albert Camus",
        "country": "Algeria, French Empire",
        "background": "static/l-etranger.jpg",
        "language": "French",
        "link": "https://en.wikipedia.org/wiki/The_Stranger_(novel)\n",
        "pages": 185,
        "title": "The Stranger",
        "year": 1942,
        "description": "Through the story of an ordinary man unwittingly drawn into a senseless murder on an Algerian beach, Camus explored what he termed 'the nakedness of man faced with the absurd.' First published in 1946; now in a new translation by Matthew Ward.",
        "isbn": "121606",
        "status": "available"
      },
      {
        "author": "Paul Celan",
        "country": "Romania, France",
        "background": "static/poems-paul-celan.jpg",
        "language": "German",
        "link": "\n",
        "pages": 320,
        "title": "Poems",
        "year": 1952,
        "description": "Paul Celan was born in 1920 in the East European province of Bukovina. Soon after his parents, German-speaking Jews, had perished at the hands of the Nazis, Celan wrote 'Todesfuge' ('Deathfugue'), the most compelling poem to emerge from the Holocaust. Self-exiled in Paris, for twenty-five years Celan continued writing in his German mother tongue, although it had 'passed through the thousand darknesses of deathbringing speech.' His writing purges and remakes that language, often achieving a hope-struck radiance never before seen in modern poetry.",
        "isbn": "121607",
        "status": "waitlist"
      },
      {
        "author": "Louis-Ferdinand Céline",
        "country": "France",
        "background": "static/voyage-au-bout-de-la-nuit.jpg",
        "language": "French",
        "link": "https://en.wikipedia.org/wiki/Journey_to_the_End_of_the_Night\n",
        "pages": 505,
        "title": "Journey to the End of the Night",
        "year": 1932,
        "description": "Céline’s masterpiece―colloquial, polemic, hyper realistic―boils over with bitter humor and revulsion at society’s idiocy and hypocrisy: Journey to the End of the Night is a literary symphony of cruelty and violence that hurtles through the improbable travels of the petit bourgeois (and largely autobiographical) antihero, Bardamu: from the trenches of WWI, to the African jungle, to New York, to the Ford Factory in Detroit, and finally to life in Paris as a failed doctor. Ralph Manheim’s pitch-perfect translation captures Céline’s savage energy, and a dynamic afterword by William T. Vollmann presents a fresh, furiously alive take on this astonishing novel.",
        "isbn": "121608",
        "status": "available"
      },
      {
        "author": "Miguel de Cervantes",
        "country": "Spain",
        "background": "static/don-quijote-de-la-mancha.jpg",
        "language": "Spanish",
        "link": "https://en.wikipedia.org/wiki/Don_Quixote\n",
        "pages": 1056,
        "title": "Don Quijote De La Mancha",
        "year": 1610,
        "description": "Don Quixote is the classic story. Called the first modern novel, this marvelous book has stood the test of time to become irrevocably intertwined with the fabric of society. Sixteenth-century Spanish gentleman Don Quixote, fed by his own delusional fantasies, takes to the road in search of chivalrous adventures. But his quest leads to more trouble than triumph. ",
        "isbn": "121609",
        "status": "available"
      },
      {
        "author": "Geoffrey Chaucer",
        "country": "England",
        "background": "static/the-canterbury-tales.jpg",
        "language": "English",
        "link": "https://en.wikipedia.org/wiki/The_Canterbury_Tales\n",
        "pages": 544,
        "title": "The Canterbury Tales",
        "year": 1450,
        "isbn": "121610",
        "status": "available"
      },
      {
        "author": "Anton Chekhov",
        "country": "Russia",
        "background": "static/stories-of-anton-chekhov.jpg",
        "language": "Russian",
        "link": "https://en.wikipedia.org/wiki/List_of_short_stories_by_Anton_Chekhov\n",
        "pages": 194,
        "title": "Stories",
        "year": 1886,
        "isbn": "121611",
        "status": "available"
      },
      {
        "author": "Joseph Conrad",
        "country": "United Kingdom",
        "background": "static/nostromo.jpg",
        "language": "English",
        "link": "https://en.wikipedia.org/wiki/Nostromo\n",
        "pages": 320,
        "title": "Nostromo",
        "year": 1904,
        "isbn": "121612",
        "status": "waitlist"
      },
      {
        "author": "Charles Dickens",
        "country": "United Kingdom",
        "background": "static/great-expectations.jpg",
        "language": "English",
        "link": "https://en.wikipedia.org/wiki/Great_Expectations\n",
        "pages": 194,
        "title": "Great Expectations",
        "year": 1861,
        "isbn": "121613",
        "status": "available"
      },
      {
        "author": "Denis Diderot",
        "country": "France",
        "background": "static/jacques-the-fatalist.jpg",
        "language": "French",
        "link": "https://en.wikipedia.org/wiki/Jacques_the_Fatalist\n",
        "pages": 596,
        "title": "Jacques the Fatalist",
        "year": 1796,
        "isbn": "121614",
        "status": "waitlist"
      },
      {
        "author": "Alfred Döblin",
        "country": "Germany",
        "background": "static/berlin-alexanderplatz.jpg",
        "language": "German",
        "link": "https://en.wikipedia.org/wiki/Berlin_Alexanderplatz\n",
        "pages": 600,
        "title": "Berlin Alexanderplatz",
        "year": 1929,
        "isbn": "121615",
        "status": "waitlist"
      },
      {
        "author": "Fyodor Dostoevsky",
        "country": "Russia",
        "background": "static/crime-and-punishment.jpg",
        "language": "Russian",
        "link": "https://en.wikipedia.org/wiki/Crime_and_Punishment\n",
        "pages": 551,
        "title": "Crime and Punishment",
        "year": 1866,
        "isbn": "121616",
        "status": "available"
      },
      {
        "author": "Fyodor Dostoevsky",
        "country": "Russia",
        "background": "static/the-idiot.jpg",
        "language": "Russian",
        "link": "https://en.wikipedia.org/wiki/The_Idiot\n",
        "pages": 656,
        "title": "The Idiot",
        "year": 1869,
        "isbn": "121617",
        "status": "available"
      },
      {
        "author": "Fyodor Dostoevsky",
        "country": "Russia",
        "background": "static/the-possessed.jpg",
        "language": "Russian",
        "link": "https://en.wikipedia.org/wiki/Demons_(Dostoyevsky_novel)\n",
        "pages": 768,
        "title": "The Possessed",
        "year": 1872,
        "isbn": "121618",
        "status": "available"
      },
      {
        "author": "Fyodor Dostoevsky",
        "country": "Russia",
        "background": "static/the-brothers-karamazov.jpg",
        "language": "Russian",
        "link": "https://en.wikipedia.org/wiki/The_Brothers_Karamazov\n",
        "pages": 824,
        "title": "The Brothers Karamazov",
        "year": 1880,
        "isbn": "121619",
        "status": "waitlist"
      },
      {
        "author": "George Eliot",
        "country": "United Kingdom",
        "background": "static/middlemarch.jpg",
        "language": "English",
        "link": "https://en.wikipedia.org/wiki/Middlemarch\n",
        "pages": 800,
        "title": "Middlemarch",
        "year": 1871,
        "isbn": "121620",
        "status": "waitlist"
      },
      {
        "author": "Ralph Ellison",
        "country": "United States",
        "background": "static/invisible-man.jpg",
        "language": "English",
        "link": "https://en.wikipedia.org/wiki/Invisible_Man\n",
        "pages": 581,
        "title": "Invisible Man",
        "year": 1952,
        "isbn": "121621",
        "status": "available"
      },
      {
        "author": "Euripides",
        "country": "Greece",
        "background": "static/medea.jpg",
        "language": "Greek",
        "link": "https://en.wikipedia.org/wiki/Medea_(play)\n",
        "pages": 104,
        "title": "Medea",
        "year": -431,
        "isbn": "121622",
        "status": "available"
      },
      {
        "author": "William Faulkner",
        "country": "United States",
        "background": "static/absalom-absalom.jpg",
        "language": "English",
        "link": "https://en.wikipedia.org/wiki/Absalom,_Absalom!\n",
        "pages": 313,
        "title": "Absalom, Absalom!",
        "year": 1936,
        "isbn": "121623",
        "status": "waitlist"
      },
      {
        "author": "William Faulkner",
        "country": "United States",
        "background": "static/the-sound-and-the-fury.jpg",
        "language": "English",
        "link": "https://en.wikipedia.org/wiki/The_Sound_and_the_Fury\n",
        "pages": 326,
        "title": "The Sound and the Fury",
        "year": 1929,
        "isbn": "121624",
        "status": "waitlist"
      },
      {
        "author": "Gustave Flaubert",
        "country": "France",
        "background": "static/madame-bovary.jpg",
        "language": "French",
        "link": "https://en.wikipedia.org/wiki/Madame_Bovary\n",
        "pages": 528,
        "title": "Madame Bovary",
        "year": 1857,
        "isbn": "121625",
        "status": "available"
      },
      {
        "author": "Gustave Flaubert",
        "country": "France",
        "background": "static/l-education-sentimentale.jpg",
        "language": "French",
        "link": "https://en.wikipedia.org/wiki/Sentimental_Education\n",
        "pages": 606,
        "title": "Sentimental Education",
        "year": 1869,
        "isbn": "121626",
        "status": "waitlist"
      },
      {
        "author": "Federico García Lorca",
        "country": "Spain",
        "background": "static/gypsy-ballads.jpg",
        "language": "Spanish",
        "link": "https://en.wikipedia.org/wiki/Gypsy_Ballads\n",
        "pages": 218,
        "title": "Gypsy Ballads",
        "year": 1928,
        "isbn": "121627",
        "status": "available"
      },
      {
        "author": "Gabriel García Márquez",
        "country": "Colombia",
        "background": "static/one-hundred-years-of-solitude.jpg",
        "language": "Spanish",
        "link": "https://en.wikipedia.org/wiki/One_Hundred_Years_of_Solitude\n",
        "pages": 417,
        "title": "One Hundred Years of Solitude",
        "year": 1967,
        "isbn": "121628",
        "status": "available"
      },
      {
        "author": "Gabriel García Márquez",
        "country": "Colombia",
        "background": "static/love-in-the-time-of-cholera.jpg",
        "language": "Spanish",
        "link": "https://en.wikipedia.org/wiki/Love_in_the_Time_of_Cholera\n",
        "pages": 368,
        "title": "Love in the Time of Cholera",
        "year": 1985,
        "isbn": "121629",
        "status": "available"
      },
      {
        "author": "Johann Wolfgang von Goethe",
        "country": "Saxe-Weimar",
        "background": "static/faust.jpg",
        "language": "German",
        "link": "https://en.wikipedia.org/wiki/Goethe%27s_Faust\n",
        "pages": 158,
        "title": "Faust",
        "year": 1832,
        "isbn": "121630",
        "status": "waitlist"
      },
      {
        "author": "Nikolai Gogol",
        "country": "Russia",
        "background": "static/dead-souls.jpg",
        "language": "Russian",
        "link": "https://en.wikipedia.org/wiki/Dead_Souls\n",
        "pages": 432,
        "title": "Dead Souls",
        "year": 1842,
        "isbn": "121631",
        "status": "waitlist"
      },
      {
        "author": "Günter Grass",
        "country": "Germany",
        "background": "static/the-tin-drum.jpg",
        "language": "German",
        "link": "https://en.wikipedia.org/wiki/The_Tin_Drum\n",
        "pages": 600,
        "title": "The Tin Drum",
        "year": 1959,
        "isbn": "121632",
        "status": "available"
      },
      {
        "author": "João Guimarães Rosa",
        "country": "Brazil",
        "background": "static/the-devil-to-pay-in-the-backlands.jpg",
        "language": "Portuguese",
        "link": "https://en.wikipedia.org/wiki/The_Devil_to_Pay_in_the_Backlands\n",
        "pages": 494,
        "title": "The Devil to Pay in the Backlands",
        "year": 1956,
        "isbn": "121633",
        "status": "available"
      },
      {
        "author": "Knut Hamsun",
        "country": "Norway",
        "background": "static/hunger.jpg",
        "language": "Norwegian",
        "link": "https://en.wikipedia.org/wiki/Hunger_(Hamsun_novel)\n",
        "pages": 176,
        "title": "Hunger",
        "year": 1890,
        "isbn": "121634",
        "status": "available"
      },
      {
        "author": "Ernest Hemingway",
        "country": "United States",
        "background": "static/the-old-man-and-the-sea.jpg",
        "language": "English",
        "link": "https://en.wikipedia.org/wiki/The_Old_Man_and_the_Sea\n",
        "pages": 128,
        "title": "The Old Man and the Sea",
        "year": 1952,
        "isbn": "121635",
        "status": "waitlist"
      },
      {
        "author": "Homer",
        "country": "Greece",
        "background": "static/the-iliad-of-homer.jpg",
        "language": "Greek",
        "link": "https://en.wikipedia.org/wiki/Iliad\n",
        "pages": 608,
        "title": "Iliad",
        "year": -735,
        "isbn": "121636",
        "status": "waitlist"
      },
      {
        "author": "Homer",
        "country": "Greece",
        "background": "static/the-odyssey-of-homer.jpg",
        "language": "Greek",
        "link": "https://en.wikipedia.org/wiki/Odyssey\n",
        "pages": 374,
        "title": "Odyssey",
        "year": -800,
        "isbn": "121637",
        "status": "available"
      },
      {
        "author": "Henrik Ibsen",
        "country": "Norway",
        "background": "static/a-Dolls-house.jpg",
        "language": "Norwegian",
        "link": "https://en.wikipedia.org/wiki/A_Doll%27s_House\n",
        "pages": 68,
        "title": "A Doll's House",
        "year": 1879,
        "isbn": "121638",
        "status": "waitlist"
      },
      {
        "author": "James Joyce",
        "country": "Irish Free State",
        "background": "static/ulysses.jpg",
        "language": "English",
        "link": "https://en.wikipedia.org/wiki/Ulysses_(novel)\n",
        "pages": 228,
        "title": "Ulysses",
        "year": 1922,
        "isbn": "121639",
        "status": "available"
      },
      {
        "author": "Franz Kafka",
        "country": "Czechoslovakia",
        "background": "static/stories-of-franz-kafka.jpg",
        "language": "German",
        "link": "https://en.wikipedia.org/wiki/Franz_Kafka_bibliography#Short_stories\n",
        "pages": 488,
        "title": "Stories",
        "year": 1924,
        "isbn": "121640",
        "status": "waitlist"
      },
      {
        "author": "Franz Kafka",
        "country": "Czechoslovakia",
        "background": "static/the-trial.jpg",
        "language": "German",
        "link": "https://en.wikipedia.org/wiki/The_Trial\n",
        "pages": 160,
        "title": "The Trial",
        "year": 1925,
        "isbn": "121641",
        "status": "available"
      },
      {
        "author": "Franz Kafka",
        "country": "Czechoslovakia",
        "background": "static/the-castle.jpg",
        "language": "German",
        "link": "https://en.wikipedia.org/wiki/The_Castle_(novel)\n",
        "pages": 352,
        "title": "The Castle",
        "year": 1926,
        "isbn": "121642",
        "status": "waitlist"
      },
      {
        "author": "Kālidāsa",
        "country": "India",
        "background": "static/the-recognition-of-shakuntala.jpg",
        "language": "Sanskrit",
        "link": "https://en.wikipedia.org/wiki/Abhij%C3%B1%C4%81na%C5%9B%C4%81kuntalam\n",
        "pages": 147,
        "title": "The recognition of Shakuntala",
        "year": 150,
        "isbn": "121643",
        "status": "waitlist"
      },
      {
        "author": "Yasunari Kawabata",
        "country": "Japan",
        "background": "static/the-sound-of-the-mountain.jpg",
        "language": "Japanese",
        "link": "https://en.wikipedia.org/wiki/The_Sound_of_the_Mountain\n",
        "pages": 288,
        "title": "The Sound of the Mountain",
        "year": 1954,
        "isbn": "121644",
        "status": "available"
      },
      {
        "author": "Nikos Kazantzakis",
        "country": "Greece",
        "background": "static/zorba-the-greek.jpg",
        "language": "Greek",
        "link": "https://en.wikipedia.org/wiki/Zorba_the_Greek\n",
        "pages": 368,
        "title": "Zorba the Greek",
        "year": 1946,
        "isbn": "121645",
        "status": "waitlist"
      },
      {
        "author": "D. H. Lawrence",
        "country": "United Kingdom",
        "background": "static/sons-and-lovers.jpg",
        "language": "English",
        "link": "https://en.wikipedia.org/wiki/Sons_and_Lovers\n",
        "pages": 432,
        "title": "Sons and Lovers",
        "year": 1913,
        "isbn": "121646",
        "status": "waitlist"
      },
      {
        "author": "Halldór Laxness",
        "country": "Iceland",
        "background": "static/independent-people.jpg",
        "language": "Icelandic",
        "link": "https://en.wikipedia.org/wiki/Independent_People\n",
        "pages": 470,
        "title": "Independent People",
        "year": 1934,
        "isbn": "121647",
        "status": "waitlist"
      },
      {
        "author": "Giacomo Leopardi",
        "country": "Italy",
        "background": "static/poems-giacomo-leopardi.jpg",
        "language": "Italian",
        "link": "\n",
        "pages": 184,
        "title": "Poems",
        "year": 1818,
        "isbn": "121648",
        "status": "available"
      },
      {
        "author": "Doris Lessing",
        "country": "United Kingdom",
        "background": "static/the-golden-notebook.jpg",
        "language": "English",
        "link": "https://en.wikipedia.org/wiki/The_Golden_Notebook\n",
        "pages": 688,
        "title": "The Golden Notebook",
        "year": 1962,
        "isbn": "121649",
        "status": "available"
      },
      {
        "author": "Astrid Lindgren",
        "country": "Sweden",
        "background": "static/pippi-longstocking.jpg",
        "language": "Swedish",
        "link": "https://en.wikipedia.org/wiki/Pippi_Longstocking\n",
        "pages": 160,
        "title": "Pippi Longstocking",
        "year": 1945,
        "isbn": "121650",
        "status": "available"
      },
      {
        "author": "Lu Xun",
        "country": "China",
        "background": "static/diary-of-a-madman.jpg",
        "language": "Chinese",
        "link": "https://en.wikipedia.org/wiki/A_Madman%27s_Diary\n",
        "pages": 389,
        "title": "Diary of a Madman",
        "year": 1918,
        "isbn": "121651",
        "status": "waitlist"
      },
      {
        "author": "Naguib Mahfouz",
        "country": "Egypt",
        "background": "static/children-of-gebelawi.jpg",
        "language": "Arabic",
        "link": "https://en.wikipedia.org/wiki/Children_of_Gebelawi\n",
        "pages": 355,
        "title": "Children of Gebelawi",
        "year": 1959,
        "isbn": "121652",
        "status": "available"
      },
      {
        "author": "Thomas Mann",
        "country": "Germany",
        "background": "static/buddenbrooks.jpg",
        "language": "German",
        "link": "https://en.wikipedia.org/wiki/Buddenbrooks\n",
        "pages": 736,
        "title": "Buddenbrooks",
        "year": 1901,
        "isbn": "121653",
        "status": "available"
      },
      {
        "author": "Thomas Mann",
        "country": "Germany",
        "background": "static/the-magic-mountain.jpg",
        "language": "German",
        "link": "https://en.wikipedia.org/wiki/The_Magic_Mountain\n",
        "pages": 720,
        "title": "The Magic Mountain",
        "year": 1924,
        "isbn": "121654",
        "status": "available"
      },
      {
        "author": "Herman Melville",
        "country": "United States",
        "background": "static/moby-dick.jpg",
        "language": "English",
        "link": "https://en.wikipedia.org/wiki/Moby-Dick\n",
        "pages": 378,
        "title": "Moby Dick",
        "year": 1851,
        "isbn": "121655",
        "status": "available"
      },
      {
        "author": "Michel de Montaigne",
        "country": "France",
        "background": "static/essais.jpg",
        "language": "French",
        "link": "https://en.wikipedia.org/wiki/Essays_(Montaigne)\n",
        "pages": 404,
        "title": "Essays",
        "year": 1595,
        "isbn": "121656",
        "status": "available"
      },
      {
        "author": "Elsa Morante",
        "country": "Italy",
        "background": "static/history.jpg",
        "language": "Italian",
        "link": "https://en.wikipedia.org/wiki/History_(novel)\n",
        "pages": 600,
        "title": "History",
        "year": 1974,
        "isbn": "121657",
        "status": "waitlist"
      },
      {
        "author": "Toni Morrison",
        "country": "United States",
        "background": "static/beloved.jpg",
        "language": "English",
        "link": "https://en.wikipedia.org/wiki/Beloved_(novel)\n",
        "pages": 321,
        "title": "Beloved",
        "year": 1987,
        "isbn": "121658",
        "status": "waitlist"
      },
      {
        "author": "Murasaki Shikibu",
        "country": "Japan",
        "background": "static/the-tale-of-genji.jpg",
        "language": "Japanese",
        "link": "https://en.wikipedia.org/wiki/The_Tale_of_Genji\n",
        "pages": 1360,
        "title": "The Tale of Genji",
        "year": 1006,
        "isbn": "121659",
        "status": "available"
      },
      {
        "author": "Robert Musil",
        "country": "Austria",
        "background": "static/the-man-without-qualities.jpg",
        "language": "German",
        "link": "https://en.wikipedia.org/wiki/The_Man_Without_Qualities\n",
        "pages": 365,
        "title": "The Man Without Qualities",
        "year": 1931,
        "isbn": "121660",
        "status": "waitlist"
      },
      {
        "author": "Vladimir Nabokov",
        "country": "Russia/United States",
        "background": "static/lolita.jpg",
        "language": "English",
        "link": "https://en.wikipedia.org/wiki/Lolita\n",
        "pages": 317,
        "title": "Lolita",
        "year": 1955,
        "isbn": "121661",
        "status": "available"
      },
      {
        "author": "George Orwell",
        "country": "United Kingdom",
        "background": "static/nineteen-eighty-four.jpg",
        "language": "English",
        "link": "https://en.wikipedia.org/wiki/Nineteen_Eighty-Four\n",
        "pages": 272,
        "title": "Nineteen Eighty-Four",
        "year": 1949,
        "isbn": "121662",
        "status": "available"
      },
      {
        "author": "Ovid",
        "country": "Roman Empire",
        "background": "static/the-metamorphoses-of-ovid.jpg",
        "language": "Classical Latin",
        "link": "https://en.wikipedia.org/wiki/Metamorphoses\n",
        "pages": 576,
        "title": "Metamorphoses",
        "year": 100,
        "isbn": "121663",
        "status": "available"
      },
      {
        "author": "Fernando Pessoa",
        "country": "Portugal",
        "background": "static/the-book-of-disquiet.jpg",
        "language": "Portuguese",
        "link": "https://en.wikipedia.org/wiki/The_Book_of_Disquiet\n",
        "pages": 272,
        "title": "The Book of Disquiet",
        "year": 1928,
        "isbn": "121664",
        "status": "waitlist"
      },
      {
        "author": "Edgar Allan Poe",
        "country": "United States",
        "background": "static/tales-and-poems-of-edgar-allan-poe.jpg",
        "language": "English",
        "link": "https://en.wikipedia.org/wiki/Edgar_Allan_Poe_bibliography#Tales\n",
        "pages": 842,
        "title": "Tales",
        "year": 1950,
        "isbn": "121665",
        "status": "available"
      },
      {
        "author": "Marcel Proust",
        "country": "France",
        "background": "static/a-la-recherche-du-temps-perdu.jpg",
        "language": "French",
        "link": "https://en.wikipedia.org/wiki/In_Search_of_Lost_Time\n",
        "pages": 2408,
        "title": "In Search of Lost Time",
        "year": 1920,
        "isbn": "121666",
        "status": "available"
      },
      {
        "author": "François Rabelais",
        "country": "France",
        "background": "static/gargantua-and-pantagruel.jpg",
        "language": "French",
        "link": "https://en.wikipedia.org/wiki/Gargantua_and_Pantagruel\n",
        "pages": 623,
        "title": "Gargantua and Pantagruel",
        "year": 1533,
        "isbn": "121667",
        "status": "waitlist"
      },
      {
        "author": "Juan Rulfo",
        "country": "Mexico",
        "background": "static/pedro-paramo.jpg",
        "language": "Spanish",
        "link": "https://en.wikipedia.org/wiki/Pedro_P%C3%A1ramo\n",
        "pages": 124,
        "title": "Pedro Páramo",
        "year": 1955,
        "isbn": "121668",
        "status": "available"
      },
      {
        "author": "Rumi",
        "country": "Sultanate of Rum",
        "background": "static/the-masnavi.jpg",
        "language": "Persian",
        "link": "https://en.wikipedia.org/wiki/Masnavi\n",
        "pages": 438,
        "title": "The Masnavi",
        "year": 1236,
        "isbn": "121669",
        "status": "waitlist"
      },
      {
        "author": "Salman Rushdie",
        "country": "United Kingdom, India",
        "background": "static/midnights-children.jpg",
        "language": "English",
        "link": "https://en.wikipedia.org/wiki/Midnight%27s_Children\n",
        "pages": 536,
        "title": "Midnight's Children",
        "year": 1981,
        "isbn": "121670",
        "status": "waitlist"
      },
      {
        "author": "Saadi",
        "country": "Persia, Persian Empire",
        "background": "static/bostan.jpg",
        "language": "Persian",
        "link": "https://en.wikipedia.org/wiki/Bustan_(book)\n",
        "pages": 298,
        "title": "Bostan",
        "year": 1257,
        "isbn": "121671",
        "status": "available"
      },
      {
        "author": "Tayeb Salih",
        "country": "Sudan",
        "background": "static/season-of-migration-to-the-north.jpg",
        "language": "Arabic",
        "link": "https://en.wikipedia.org/wiki/Season_of_Migration_to_the_North\n",
        "pages": 139,
        "title": "Season of Migration to the North",
        "year": 1966,
        "isbn": "121672",
        "status": "waitlist"
      },
      {
        "author": "José Saramago",
        "country": "Portugal",
        "background": "static/blindness.jpg",
        "language": "Portuguese",
        "link": "https://en.wikipedia.org/wiki/Blindness_(novel)\n",
        "pages": 352,
        "title": "Blindness",
        "year": 1995,
        "isbn": "121673",
        "status": "available"
      },
      {
        "author": "William Shakespeare",
        "country": "England",
        "background": "static/hamlet.jpg",
        "language": "English",
        "link": "https://en.wikipedia.org/wiki/Hamlet\n",
        "pages": 432,
        "title": "Hamlet",
        "year": 1603,
        "isbn": "121674",
        "status": "available"
      },
      {
        "author": "William Shakespeare",
        "country": "England",
        "background": "static/king-lear.jpg",
        "language": "English",
        "link": "https://en.wikipedia.org/wiki/King_Lear\n",
        "pages": 384,
        "title": "King Lear",
        "year": 1608,
        "isbn": "121675",
        "status": "waitlist"
      },
      {
        "author": "William Shakespeare",
        "country": "England",
        "background": "static/othello.jpg",
        "language": "English",
        "link": "https://en.wikipedia.org/wiki/Othello\n",
        "pages": 314,
        "title": "Othello",
        "year": 1609,
        "isbn": "121676",
        "status": "waitlist"
      },
      {
        "author": "Sophocles",
        "country": "Greece",
        "background": "static/oedipus-the-king.jpg",
        "language": "Greek",
        "link": "https://en.wikipedia.org/wiki/Oedipus_the_King\n",
        "pages": 88,
        "title": "Oedipus the King",
        "year": -430,
        "isbn": "121677",
        "status": "available"
      },
      {
        "author": "Stendhal",
        "country": "France",
        "background": "static/le-rouge-et-le-noir.jpg",
        "language": "French",
        "link": "https://en.wikipedia.org/wiki/The_Red_and_the_Black\n",
        "pages": 576,
        "title": "The Red and the Black",
        "year": 1830,
        "isbn": "121678",
        "status": "available"
      },
      {
        "author": "Laurence Sterne",
        "country": "England",
        "background": "static/the-life-and-opinions-of-tristram-shandy.jpg",
        "language": "English",
        "link": "https://en.wikipedia.org/wiki/The_Life_and_Opinions_of_Tristram_Shandy,_Gentleman\n",
        "pages": 640,
        "title": "The Life And Opinions of Tristram Shandy",
        "year": 1760,
        "isbn": "121679",
        "status": "waitlist"
      },
      {
        "author": "Italo Svevo",
        "country": "Italy",
        "background": "static/confessions-of-zeno.jpg",
        "language": "Italian",
        "link": "https://en.wikipedia.org/wiki/Zeno%27s_Conscience\n",
        "pages": 412,
        "title": "Confessions of Zeno",
        "year": 1923,
        "isbn": "121680",
        "status": "available"
      },
      {
        "author": "Jonathan Swift",
        "country": "Ireland",
        "background": "static/gullivers-travels.jpg",
        "language": "English",
        "link": "https://en.wikipedia.org/wiki/Gulliver%27s_Travels\n",
        "pages": 178,
        "title": "Gulliver's Travels",
        "year": 1726,
        "isbn": "121681",
        "status": "available"
      },
      {
        "author": "Leo Tolstoy",
        "country": "Russia",
        "background": "static/war-and-peace.jpg",
        "language": "Russian",
        "link": "https://en.wikipedia.org/wiki/War_and_Peace\n",
        "pages": 1296,
        "title": "War and Peace",
        "year": 1867,
        "isbn": "121682",
        "status": "waitlist"
      },
      {
        "author": "Leo Tolstoy",
        "country": "Russia",
        "background": "static/anna-karenina.jpg",
        "language": "Russian",
        "link": "https://en.wikipedia.org/wiki/Anna_Karenina\n",
        "pages": 864,
        "title": "Anna Karenina",
        "year": 1877,
        "isbn": "121683",
        "status": "available"
      },
      {
        "author": "Leo Tolstoy",
        "country": "Russia",
        "background": "static/the-death-of-ivan-ilyich.jpg",
        "language": "Russian",
        "link": "https://en.wikipedia.org/wiki/The_Death_of_Ivan_Ilyich\n",
        "pages": 92,
        "title": "The Death of Ivan Ilyich",
        "year": 1886,
        "isbn": "121684",
        "status": "waitlist"
      },
      {
        "author": "Mark Twain",
        "country": "United States",
        "background": "static/the-adventures-of-huckleberry-finn.jpg",
        "language": "English",
        "link": "https://en.wikipedia.org/wiki/Adventures_of_Huckleberry_Finn\n",
        "pages": 224,
        "title": "The Adventures of Huckleberry Finn",
        "year": 1884,
        "isbn": "121685",
        "status": "waitlist"
      },
      {
        "author": "Valmiki",
        "country": "India",
        "background": "static/ramayana.jpg",
        "language": "Sanskrit",
        "link": "https://en.wikipedia.org/wiki/Ramayana\n",
        "pages": 152,
        "title": "Ramayana",
        "year": -450,
        "isbn": "121686",
        "status": "waitlist"
      },
      {
        "author": "Virgil",
        "country": "Roman Empire",
        "background": "static/the-aeneid.jpg",
        "language": "Classical Latin",
        "link": "https://en.wikipedia.org/wiki/Aeneid\n",
        "pages": 442,
        "title": "The Aeneid",
        "year": -23,
        "isbn": "121687",
        "status": "available"
      },
      {
        "author": "Vyasa",
        "country": "India",
        "background": "static/the-mahab-harata.jpg",
        "language": "Sanskrit",
        "link": "https://en.wikipedia.org/wiki/Mahabharata\n",
        "pages": 276,
        "title": "Mahabharata",
        "year": -700,
        "isbn": "121688",
        "status": "available"
      },
      {
        "author": "Walt Whitman",
        "country": "United States",
        "background": "static/leaves-of-grass.jpg",
        "language": "English",
        "link": "https://en.wikipedia.org/wiki/Leaves_of_Grass\n",
        "pages": 152,
        "title": "Leaves of Grass",
        "year": 1855,
        "isbn": "121689",
        "status": "available"
      },
      {
        "author": "Virginia Woolf",
        "country": "United Kingdom",
        "background": "static/mrs-dalloway.jpg",
        "language": "English",
        "link": "https://en.wikipedia.org/wiki/Mrs_Dalloway\n",
        "pages": 216,
        "title": "Mrs Dalloway",
        "year": 1925,
        "isbn": "121690",
        "status": "waitlist"
      },
      {
        "author": "Virginia Woolf",
        "country": "United Kingdom",
        "background": "static/to-the-lighthouse.jpg",
        "language": "English",
        "link": "https://en.wikipedia.org/wiki/To_the_Lighthouse\n",
        "pages": 209,
        "title": "To the Lighthouse",
        "year": 1927,
        "isbn": "121691",
        "status": "available"
      },
      {
        "author": "Marguerite Yourcenar",
        "country": "France/Belgium",
        "background": "static/memoirs-of-hadrian.jpg",
        "language": "French",
        "link": "https://en.wikipedia.org/wiki/Memoirs_of_Hadrian\n",
        "pages": 408,
        "title": "Memoirs of Hadrian",
        "year": 1951,
        "isbn": "121692",
        "status": "available"
      }
    ],
    search: "",
    reservations: [],
    notification: {
      visible: false,
      material: ""
    }
  }
}).$mount('#app')
